<?php
      //  Author:  Tiffany Kalin
      //  Contact: Jonathan Godt,
      //  Last  modified: 03/07/2016
      if  (!isset($TEMPLATE))  {
      $TITLE  =  'Landslide Overview Map of the Conterminous United States';
      $NAVIGATION  = true;
      include  'template.inc.php';
      }
?>
<h3>The Map</h3>

<img src="images/nationalmap.jpg" width="600" height="374" border="0" alt="National Landslide map" usemap="#nationalmap_Map">
<map name="nationalmap_Map">
<area shape="rect" coords="12,255,106,373" href="legend.php" alt="Larger image of map legend" />
<area shape="rect" coords="111,299,149,347" href="click.php" alt="Explaination of hotspots" />

<area shape="circle" coords="497,86,8" href="images/ane.gif" alt="Northeast U.S." />
<area shape="circle" coords="431,80,8" href="images/michigan.gif" alt="Great Lakes area U.S." />
<area shape="circle" coords="420,138,8" href="images/ecentral.gif" alt="Eastern U.S." />
<area shape="circle" coords="370,201,8" href="images/ase.gif" alt="Southeast U.S." />
<area shape="circle" coords="295,199,8" href="images/midwest.gif" alt="Midwest U.S." />
<area shape="circle" coords="114,181,7" href="images/psw.gif" alt="Southwest U.S." />
<area shape="circle" coords="123,79,8" href="images/pnw.gif" alt="Northwest U.S." />
</map>

<div class="row">
  <div class="column one-of-two">
    <h3>Introduction </h3>

    <p>The accompanying map is a preliminary digital version of Geological Survey Professional Paper 1183, Landslide Overview Map of the Conterminous United States, by Dorothy H. Radbruch-Hall, Roger B. Colton, William E. Davies, Ivo Lucchitta, Betty A. Skipp, and David J. Varnes, 1982. This map and the original delineate areas where large numbers of landslides have occurred and areas which are susceptible to landsliding in the conterminous United States. </p>
    <h3>Methods used to compile map </h3>

    <p>In compiling the original map, the authors considered landslides to be any downward and outward movement of earth materials on a slope. Not included in the compilation were talus deposits, deposits resulting from ancient landslides not related to present slopes, large gravitational thrust sheets, solifluction deposits, snow avalanches, and debris deposited by flows that contribute to alluvial fans in arid regions. Individual landslides could not be shown at this scale. The map was prepared by evaluating formations or  groups of formations shown on the geologic map of the United States (King and Beikman, 1974) as being of high, medium, or low susceptibility to landsliding and classified the formations as having high, medium, or low landslide incidence (number of landslides). Susceptibility to landsliding was defined as the probable degree of response of the areal rocks and soils to natural or artificial cutting or loading of slopes or to anomalously high precipitation. High, medium, and low susceptibility are delimited by the percentages given below for classifying the incidence of landsliding. Susceptibility is not indicated where lower than incidence. The effect on slope stability caused by earthquakes was not evaluated, although many catastrophic landslides have been generated by ground  shaking during earthquakes. Areas susceptible to ground failure under static conditions would probably also be susceptible to failure during earthquakes.</p>

    <p>In areas of continental glaciation, additional data were used to identify surficial deposits that are susceptible to slope movement The map units were classified into three incidence categories according to the percentage of the area involved in landslide processes. Area involved in landsliding Incidence &gt;15% High 1.5-15% Medium &lt;1.5% Low. Published data were used whenever possible for the original map. In many places, the percentage of a formation involved in landsliding, as shown on large-scale published maps, was determined by counting squares of a superimposed grid. Formations shown on the large-scale maps were then correlated with geologic units on the geologic map of the United States. Aerial photography, newspaper accounts, fieldwork, and other published data were used in other areas. For many parts of the country, however, particularly for parts of the Western United States, information on landslides and their relation to geologic  conditions is sparse. Data from the relatively small number of geologic maps and reports that give detailed information on slope stability in scattered places, were therefore extrapolated as accurately as possible into adjacent areas.  Although both slope angle and precipitation influence slope stability, full weight was not given to these factors in preparing the original map. At that time no slope map or detailed precipitation map existed at a suitable scale for the entire United States. </p>

    <p>The susceptibility categories are largely subjective because insufficient data were available for precise determinations. Where source maps show slope movement for one part of a geologic unit but not for others, it is generally unknown whether the absence of recorded landslides indicates a difference in natural conditions or simply a scarcity of information on landslides for those parts of the unit. Generally, the authors assumed that anomalous precipitation or changes in existing conditions can initiate landslide  movement in rocks and soils that have numerous landslides in parts of their outcrop areas. Because the map is highly generalized, owing to the small scale and the scarcity of precise landslide information for much of  the country, it is unsuitable for local planning or actual site selection.</p>

    <h3>Methods used to prepare digital version</h3>

    <p>The original 1 : 3,750,00 mylar manuscripts were digitized using ARC/INFO 7.0.4 running under Solaris CDE 1.0.2 on a UNIX workstation. The polygons were then closed at International boundaries and coastlines using a coverage derived from 1 : 1,000,000 Digital Chart of the World. Each landslide polygon was given an attribute describing the percentage of incidence and/or susceptibility. The landslide polygon  are attributed with SLIDE-ATT which indicates landslide incidence and susceptibility as INC-LOW, INC- MOD, INC-HIGH, SUS-MOD, SUS-HIGH, COMBO-HIGH. The arcs are attributed with the item POLNTYPE indicating whether the arc encloses a landslide polygon, coastline, or international border.  </p>

    <h3>References</h3>

    <ul class="referencelist">

      <li><a href="http://pubs.usgs.gov/pp/p1183/pp1183.html" target="_blank" class="offsite">Radbruch-Hall, D.H., R.B. Colton, W.E. Davies, Ivo Lucchitta, B.A. Skipp, and D.J. Varnes, 1982, Landslide Overview Map of the Conterminous United States</a>, Geological Survey Professional Paper 1183, U.S. Geological Survey, Washington.</li>

      <li>King, P.B., and Beikman, H.M., 1974, Geologic map of the United States (exclusive of Alaska and Hawaii) U.S. Geological Survey, scale 1:2,500,000, 2 sheets.</li>
    </ul>
  </div>

  <div class="column one-of-two">
    <h3>Open-File Report 97-289</h3>
    <p><a href="http://pubs.er.usgs.gov/publication/ofr97289">Digital Compilation of <strong>Landslide Overview Map of the Conterminous United States</a><em> By Dorothy  H. Radbruch-Hall, Roger B. Colton, William E. Davies, Ivo Lucchitta, Betty A. Skipp, and  David J. Varnes, 1982</em></strong><br />
    by  Jonathan W. Godt  </p>

    <ul class="separator">
      <li>
        <a href="ftp://hazards.cr.usgs.gov/web/landslides-website/Landslide-US-Overview-GIS.zip" class="offsite">Shapefiles of the landslide data</a>
      </li>
      <li>
        <a href="http://pubs.usgs.gov/of/1997/ofr-97-0289/" class="offsite">Tarred and gzipped ArcInfo AMLS and associated text files (500mb when decompressed)</a>
      </li>
    </ul>
  </div>

</div>
