<?php
      //  Author:  Lisa Wald
      //  Contact:  Jonathan Godt
      if  (!isset($TEMPLATE))  {
      $TITLE  =  'Preliminary Locations of Landslide Impacts from Hurricane Maria, Puerto Rico';
      $NAVIGATION  = true;
      include  'template.inc.php';
      }
?>

<h2>Disclaimer</h2>
<p>
  This information is preliminary or provisional and is subject to revision. It is being provided to meet the need for timely science to assess ongoing hazards. The information has not received final approval by the U.S. Geological Survey (USGS) and is provided on the condition that neither the USGS nor the U.S. Government shall be held liable for any damages resulting from the authorized or unauthorized use of the information.
</p>

<h2>October 25, 2017: Map data showing concentration of landslides caused by Hurricane Maria in Puerto Rico
</h2>

<p>
  Erin K. Bessette-Kirton, Jeffrey A. Coe, Jonathan W. Godt, Jason W. Kean, Francis K. Rengers, William H. Schulz, Rex L. Baum, Eric S. Jones, and Dennis M. Staley
</p>
<p>
  On September 20, 2017, Hurricane Maria hit the U.S. territory of Puerto Rico as a category 4 storm. Heavy rainfall caused landslides in mountainous regions throughout the territory. This data release presents geospatial data describing the concentration of landslides generated by Hurricane Maria in Puerto Rico. We used post-hurricane satellite and aerial imagery collected between September 26, 2017 and October 8, 2017 to visually estimate the concentration of landslides over nearly the whole territory. This was done by dividing the territory into a grid with 4 square km cells (2 km x 2 km). Each 4 square km grid cell was classified as either containing no landslides, fewer than 25 landslides/ square km or more than 25 landslides/ square km. We used 12 WorldView satellite images (~0.5 m-resolution) available from Digital Globe, Inc. and ~0.15 m-resolution aerial imagery collected by Sanborn and QuantumSpatial (http://www.arcgis.com/home/item.html?id=b1949283c1084b0daf2987d896392ac2). We identified landslides by locating areas with exposed soil or rock and morphology typical of landslides. Because leaves were stripped from much of the vegetation, landslide scars were readily visible in both sources of imagery. We assume that the majority of landslides were triggered by rainfall from Hurricane Maria, but rainfall from Hurricane Irma during the first week of September and rainfall from thunderstorms after Hurricane Maria may have also initiated landslides.
</p>
<p>
  On September 20, 2017, Hurricane Maria hit the U.S. territory of Puerto Rico as a category 4 storm. Heavy rainfall caused landslides in mountainous regions throughout the territory. This data release presents geospatial data describing the concentration of landslides generated by Hurricane Maria in Puerto Rico. We used post-hurricane satellite and aerial imagery collected between September 26, 2017 and October 8, 2017 to visually estimate the concentration of landslides over nearly the whole territory. This was done by dividing the territory into a grid with 4 square km cells (2 km x 2 km). Each 4 square km grid cell was classified as either containing no landslides, fewer than 25 landslides/ square km or more than 25 landslides/ square km. We used 12 WorldView satellite images (~0.5 m-resolution) available from Digital Globe, Inc. and ~0.15 m-resolution aerial imagery collected by Sanborn and QuantumSpatial (http://www.arcgis.com/home/item.html?id=b1949283c1084b0daf2987d896392ac2). We identified landslides by locating areas with exposed soil or rock and morphology typical of landslides. Because leaves were stripped from much of the vegetation, landslide scars were readily visible in both sources of imagery. We assume that the majority of landslides were triggered by rainfall from Hurricane Maria, but rainfall from Hurricane Irma during the first week of September and rainfall from thunderstorms after Hurricane Maria may have also initiated landslides.
</p>

<p>
  <a href="https://www.sciencebase.gov/catalog/item/59de6459e4b05fe04ccd39d8">ScienceBase Catalog Page</a>
</p>

<figure>
  <a href="images/PR_Maria_LS_density_map.pdf"><img src='images/PR_Maria_LS_density_map.jpg' alt=''/></a>
  <figcaption>
    Gridded map of Puerto Rico showing the concentration of landslides. Dark red squares are grid areas with &gt;25 landslides/km<sup>2</sup>, red squares are grid areas with &lt;25 landslides/km<sup>2</sup>, white squares are grid areas with no landslides, and gray squares indicate the grid was not examined. <strong>Click on image to view a hi-resolution PDF image</strong>.
  </figcaption>
</figure>

<h2>October 3, 2017</h2>

<p>
  Rainfall from Hurricane Maria triggered landslides in the mountainous areas of Puerto Rico. We are examining high-resolution optical satellite imagery to identify locations of roads, other infrastructure, and buildings impacted by landslides. We estimate the accuracy of impact locations to be approximately 100 m (328 ft) based on comparison of preliminary post-storm with pre-storm images. That is, the point locations provided in the database are accurate to only within a 100 m (328 ft) of their actual locations on the ground. The inventory of landslide impacts is likely incomplete even for areas where imagery is available because some impacts may be obscured by clouds, vegetation, or shadows. The purpose of this report and accompanying geospatial data is to assist response and recovery efforts.
</p>
<p>
  The geospatial database is comprised of polygons outlining the extent of currently available imagery, points showing the locations of landslide impacts, and polygons defining a 100 m (328 ft) buffer around point locations are provided as part of the geospatial database to provide information on estimated location accuracy. Points show the locations of roads and other transportation infrastructure, facilities and buildings undermined by landslides, buried in landslide debris, or otherwise impacted by landslides at the time of the collection of the satellite imagery.
</p>
<p>
  The report and geospatial data are incomplete, but will be updated as additional imagery becomes available.
</p>

<p><a href="PR_Maria_LS.zip">Download GeoDatabase, Metadata, and Readme Files</a> (ZIP file)</p>

<figure>
  <img src='images/PR_full_Mariav1.jpg' alt=''/>
  <figcaption>
  </figcaption>
</figure>

<figure>
  <img src='images/PR_inset_Mariav1.jpg' alt=''/>
  <figcaption>
  </figcaption>
</figure>

<figure>
  <img src='images/181458N665302W.jpg' alt=''/>
  <figcaption>
    Excerpt of satellite image showing landslide impacts to Highway PR-431 and houses near the Rio Blanco in the Lares Municipality. Points identify the approximate location of roads and buildings visibly impacted by landslides. Image filename contains approximate latitude and longitude of impact location.
  </figcaption>
</figure>

<figure>
  <img src='images/181117N665943W.jpg' alt=''/>
  <figcaption>
    Excerpt of satellite image showing landslide impacts to PR-357 near the Río Rosario in the Maricao Municipality. Points identify the approximate road locations visibly impacted by landslides. Image filename contains approximate latitude and longitude of impact location.
  </figcaption>
</figure>

<figure>
  <img src='images/181414N_-665023W.jpg' alt=''/>
  <figcaption>
    Excerpt of satellite image showing landslide impacts to roads in the Lares Municipality. Points identify the approximate road locations visibly impacted by landslides. Image filename contains approximate latitude and longitude of impact location.
  </figcaption>
</figure>

<figure>
  <img src='images/182352N670358W.jpg' alt=''/>
  <figcaption>
    Excerpt of satellite image showing landslide impacts to Highway PR-444 and buildings in the Moca Municipality. Points identify the approximate location of roads and buildings visibly impacted by landslides. Image filename contains approximate latitude and longitude of impact location.
  </figcaption>
</figure>

<figure>
  <img src='images/181642N670437W.jpg' alt=''/>
  <figcaption>
    Excerpt of satellite image showing landslide impacts to Highway PR-109 and buildings in the Anasco Municipality. Points identify the approximate location of roads and buildings visibly impacted by landslides. Image filename contains approximate latitude and longitude of impact location.
  </figcaption>
</figure>

<figure>
  <img src='images/181556N670443W.jpg' alt=''/>
  <figcaption>
    Excerpt of satellite image showing landslide impacts near Highway PR-406 and buildings in the Anasco Municipality. Points identify the approximate location of roads and buildings visibly impacted by landslides. Image filename contains approximate latitude and longitude of impact location.
  </figcaption>
</figure>

<figure>
  <img src='images/181125N665408W.jpg' alt=''/>
  <figcaption>
    Excerpt of satellite image showing landslide impacts to a road in the southeast corner of Las Marias Municipality. Points identify the approximate location of roads visibly impacted by landslides. Image filename contains approximate latitude and longitude of impact location.
  </figcaption>
</figure>

<figure>
  <img src='images/181508N665213W.jpg' alt=''/>
  <figcaption>
    Excerpt of satellite image showing landslide impacts to roads, agriculture, and a reservoir in the Lares Municipality. Points identify the approximate location of roads visibly impacted by landslides. Image filename contains approximate latitude and longitude of this impact location.
  </figcaption>
</figure>
