<?php
$project_descriptions = array(

	"Hazard Assessments" => "<strong>Landslide Hazard Assessments Research</strong>: &nbsp;Research on hazardous landslide processes, including their mechanisms, recurrence, distribution, and probability is the main activity of this project.  The objective of our research is to improve understanding of the processes and develop physically based procedures for deterministic and probabilistic landslide hazard assessment.  The principal study area is currently western Oregon; studies are also being conducted in selected areas of Washington State, Colorado, and California.  Research in Oregon is being conducted in cooperation with the <a href=\"http://www.oregongeology.org/sub/default.htm\" target=\"_blank\" class=\"offsite\">Oregon Department of Geology and Mineral Industries (DOGAMI)</a> with focus on major hazardous landslide processes affecting western Oregon, particularly debris flow and reactivation of large, deep landslides. ",

	"National Landslide Information Center" => "<strong>National Landslide Information Center</strong>: &nbsp;Economic losses from landslides occur in every state and territory of the U.S.  Improved public awareness of landslides and the hazards they pose to property and public safety is necessary to achieve significant reduction in landslide related losses.  The National Landslide Information Center (NLIC) in Golden, Colorado conducts outreach for the Landslide Hazard Program. These activities are undertaken to promote awareness of the national landslide problem, assist professionals and the general public in locating appropriate landslide information (maps and other literature), to promote awareness of USGS products and services related to landslides.",

	"Real-Time Landslide Monitoring" => "<strong>Real-Time Monitoring and Landslide Process Research</strong>: &nbsp;Catastrophic landsliding is an inherently transient process; accurate understanding requires real-time or near real-time monitoring of both triggering phenomena and landslide activity.  USGS landslide monitoring and related field studies of landslide processes provide information needed to constrain alert and warning thresholds, and document processes that precede (and therefore can be used to help predict) landslide catastrophes.  This research relies on many kinds of field instrumentation to monitor landslide activity and processes as well as complex mathematical models to interpret the results.  USGS landslide monitoring research contributes to the eventual goal of accurately forecasting landslide catastrophes.",

	"Rapid Landslide Assessment" => "<strong>Rapid Landslide Assessment</strong>: &nbsp;The USGS maintains rapid response capabilities to provide technical expertise and assistance to Federal, state and local government agencies (as well as international agencies) before, during and after major landslide disasters.  Rapid response teams provide technical consultation, field instrumentation and monitoring, and postdisaster documentation to fulfill official requests from other federal, state and local agencies, as well as occasional requests from foreign countries (through USAID or OFDA).  In connection with post disaster responses, USGS rapid response teams conduct mapping and field studies to improve the predictive understanding of landslides and debris flows needed to reduce losses from future landslide catastrophes.  ",

	"Southern California Landslide Hazard Assessment" => "<strong>Southern California Landslide Hazard Research</strong>: &nbsp;Southern California is one of the most hazardous landslide regions in the United States; previous studies have documented shallow rapid soil slips and ensuing debris flows as well as deep-seated, slow-moving landslides throughout the region.  USGS research is leading to new methods to portray the hazards from different types of landslides along the southern California coast.  We are applying new technologies, methods, and models to the difficult problem of predicting different styles of landslide movement from similar geologic materials. These approaches include LiDAR (Light Detection And Ranging) imagery and analysis of digital landscape signatures for characterizing different mass wasting settings, critical state soil mechanics tests for determining the likelihood of a landslide transforming into a debris flow, and recently developed numerical models for predicting debris-flow inundation.",

	"Post-Fire Debris Flow Susceptibility" => "<strong>Post-Fire Debris Flow Susceptibility</strong>: &nbsp;In recent years, wildfires have ravaged many areas throughout the western U.S. Rainstorms that come in the wake of these fires often cause flooding and debris flows. The destructive debris flows have recently taken dozens of lives and caused many millions of dollars in damage. USGS research on debris flows in burned areas focuses on determining the conditions and processes that cause debris flows and rapidly assessing the potential for debris flow in specific burned areas."

);

?>
