<?php
      //  Author:  Tiffany Kalin
      //  Contact:  Jonathan Godt,
      if  (!isset($TEMPLATE))  {
      $TITLE  =  'Rainfall and Landslides in Northern and Central California';
      $NAVIGATION  = true;
      include  'template.inc.php';
      }
?>

<figure class="right" style="width:350px">
  <img src="images/berkeley.jpg" alt="photo of Berkeley Hills showing a small landslide"/>
  <figcaption>
  A landslide in the Berkeley hills of the San Francisco Bay area during April 2006.  The black tarps cover the headscarp (top of landslide) in order to prevent additional infiltration by rainfall. (Photo Credit, Brian Collins, USGS)
  </figcaption>
</figure>

<p>
  California is well-known to be susceptible to landslides (see <a href="https://pubs.er.usgs.gov/publication/ofr0317">Preliminary soil-slip susceptibility maps, southwestern California</a> - USGS Open-File Report 2003-17).  Landslides in the state generally occur due to precipitation, and to a lesser extent, earthquakes.  Historically, large winter storms have caused the most damage, and in the highly developed San Francisco Bay area these impacts have sometimes been quite severe causing both fatalities and significant property damage (for example the January 1982 winter storm - see <a href="http://pubs.usgs.gov/pp/1988/1434/">USGS Professional Paper 1434</a>).
</p>
<p>
  <a href="http://geochange.er.usgs.gov/sw/changes/natural/elnino/">El Ni&ntilde;o</a> (1997-98 info), the warm phase of the El Ni&ntilde;o Southern Oscillation (commonly called ENSO), is associated with a band of warm central and east-central equatorial Pacific Ocean water (see <a href="http://www.elnino.noaa.gov/">NOAA El Ni&ntilde;o Portal</a>). ENSO cycles are known to cause global changes of both temperatures and rainfall. Although some rainy winter seasons in California are related to El Ni&ntilde;o events (see <a href="http://www.cpc.ncep.noaa.gov/products/analysis_monitoring/ensostuff/ensoyears.shtml">NOAA National Weather Service Oceanic Ni&ntilde;o Index</a>), not all El Ni&ntilde;o periods have resulted in significant precipitation (see <a href="http://ca.gov/Drought/pdf/Drought_ENSO_handout.pdf">"Will El Ni&ntilde;o Make a Difference? Maybe Not"</a> - California Dept. of Water Resources).
</p>
<p>
  The USGS conducts active research on identifying the triggering mechanisms and hazards associated with landsliding.  In northern and central California, research efforts have predominantly focused on the San Francisco Bay area, and a number of research products are available that showcase the landslide effects of previous large winter storms to the region, including some related to El Ni&ntilde;o events.  These reports and maps can be used as examples of what may occur during the upcoming 2015-2016 El Ni&ntilde;o season if heavy precipitation occurs.
</p>
<ul>
  <li><a href="http://pubs.usgs.gov/mf/0327/plate-1.pdf">Effects of the 1968-1969 El Ni&ntilde;o</a> (21.5MB PDF)</li>
  <li><a href="images/M679-300dpi.pdf">Effects of the 1972-1973 El Ni&ntilde;o</a></li>
  <li><a href="http://pubs.usgs.gov/pp/1988/1434/">Effects of the January 3-5, 1982 storm</a></li>
  <li><a href="http://pubs.usgs.gov/of/1997/of97-745/">Preparation for the 1997-1998 El Ni&ntilde;o</a></li>
  <li><a href="http://pubs.usgs.gov/mf/1999/mf-2325/">Effects of the 1997-1998 El Ni&ntilde;o</a></li>
  <li><a href="http://pubs.usgs.gov/mf/2002/mf-2384/">Effects of the February 2-3, 1998 storm</a></li>
  <li><a href="http://pubs.usgs.gov/sim/2004/2859/">Effects of the 1997-1998 El Ni&ntilde;o in the East Bay</a></li>
</ul>

<h2>Shallow Landslides and Debris Flows</h2>

<figure class="left" style="width:300px">
  <img src="images/unioncity.jpg" alt="photo of multiple small landslides on grassy hillside"/>
  <figcaption>
    Shallow landslides turned into debris flows on many of the hillslopes near Union City in the East Bay hills of the San Francisco Bay area during a storm in February 1998. (Photo by Mark Reid, USGS)
  </figcaption>
</figure>

<p>
  Shallow landslides are generally those less than 3-5 m (10-15 ft) in depth.  When shallow landslides are sufficiently wet, they may move rapidly and can be highly mobile over long distances &ndash; these are termed debris flows.  Whereas shallow landslides can cause property and infrastructure damage, and clog streams and drainages, debris flows are more likely to cause injuries and fatalities through their ability to move quickly and with large amounts of debris (soil, boulders, trees, etc.).  Shallow landslides and debris flows are most often generated by intense rainfall, with rainfall rates measured in tens of millimeters per hour (few to several inches per hour) (see <a href="http://pubs.usgs.gov/of/1997/of97-745/of97-745f.html">USGS Open File Report 97-745F</a>).
</p>
<p>
  Shallow landslides can occur at any point during a winter season in the San Francisco Bay area, but most often occur once the ground is nearly saturated &ndash; this typically occurs after the first few winter storms come in the November and December timeframe.  These conditions, termed the &ldquo;antecedent moisture conditions&rdquo; have been correlated with seasonal rainfall and maps are available based on previous storms (see <a href="http://pubs.usgs.gov/pp/1988/1434/">USGS Professional Paper 1434 Plate 1</a>).
</p>
<p>
  Generally, researchers have found that at least 25 cm (10 in) of rainfall is needed to nearly saturate the ground on San Francisco Bay area hillslopes.  Because antecedent conditions do not account for drying and evaporation between storms, USGS researchers have been developing methods to monitor the soil moisture of landslide prone hillslopes directly.  This <a href="http://landslides.usgs.gov/docs/collins/Collins_et_al_-_Monitoring_shallow_landslides_in_SFB_California.pdf">research project</a> aims to quantify the soil moisture conditions responsible for shallow landslides and consequent debris flows.
</p>
<p>
  It is often hard to identify exactly where shallow landslides and debris flows will occur.  Instead, researchers use models to develop debris flow susceptibility maps that are, in turn, based on measurements of soil type and depth, and topographic slope and shape.  Debris flow source area maps based on measured topographic parameters are available for the entire San Francisco Bay area (see <a href="http://pubs.usgs.gov/of/1997/of97-745/of97-745e.html">USGS Open File Report 97-745E</a>) &ndash; these indicate areas with hazard potential for debris flows should seasonal cumulative rainfall and storm rainfall intensity thresholds be exceeded.  Storm rainfall thresholds have also been calculated for the entire San Francisco Bay area (see <a href="http://pubs.usgs.gov/of/1997/of97-745/of97-745f.html">USGS Open File Report 97-745F</a>).
</p>

<h2>Deep-seated Landslides</h2>

<figure class="left" style="width:300px">
  <img src="images/aptos.jpg" alt="photo of grassy hillside with large landslide"/>
  <figcaption>
  A deep-seated landslide in the Santa Cruz mountains of the San Francisco Bay area during April 1998.  Multiple scarps (sliding planes) are visible with the trees tilted backwards and the house tilted forwards. (Photo by Robert Schuster, USGS)
  </figcaption>
</figure>

<p>
  Deep-seated landslides are generally those greater than 3-5 m (10-15 ft) in depth.  These landslides are often generated by prolonged above-average rainfall, such as can occur during El Ni&ntilde;o years, although even &ldquo;normal&rdquo; precipitation years in northern and central California can lead to landslide initiation.  Typically, deep-seated landslides occur towards the end of the winter season (March, April, May) due to the time it takes for seasonal rainfall to reach the bottom, &ldquo;slip surface&rdquo; of the landslide.  However, heavy rain earlier in the season can also have this effect.  Often, deep-seated landslides lay dormant for lengthy periods of time.
</p>
<p>
  Many deep-seated landslides have been mapped in the San Francisco Bay area (see <a href="http://pubs.usgs.gov/of/1997/of97-745/of97-745c.html">USGS Open File Report 97-745C</a>), and often a qualified geotechnical engineer or engineering geologist may be able to determine if particular properties are on or susceptible to landslide movement.  In 1997, the USGS developed a simple way to determine the locations of landslides that have occurred in the past throughout the San Francisco Bay Area by referencing published topographic quadrangle maps (see <a href="http://pubs.usgs.gov/of/1997/of97-745/of97-745d.html">USGS Open File Report 97-745D</a>).
</p>
<p>
  Generally, deep-seated landslides do not cause injuries or fatalities; rather, they move slowly and can severely distort and damage buildings and infrastructure such as roads and pipelines.  Sometimes, smaller shallow landslides can initiate from the bottom (or toe) of deep-seated landslides.  In these cases, the hazard of the shallow landslides turning into debris flows should be assessed.
</p>

<div class="clear"></div>

<h2>Recent Burned Areas</h2>

<figure class="right" style="width:300px">
  <img src="images/bigsur2008.png" alt="photo of brown debris flow on steep slope"/>
  <figcaption>
    Debris flow from steep slopes in the Big Sur area of central California that resulted from rains following the 2008 Basin Complex fire.  With little vegetation to hold soil in place, channels may fill with sediment that can then be triggered into debris flows by heavy rainfall. (Photo by Kevin Schmidt, USGS)
  </figcaption>
</figure>

<p>
  Steep, recently burned areas are especially susceptible to debris flows. Even modest rain storms during normal, non-El Ni&ntilde;o years can trigger <a href="/research/wildfire/">post-wildfire debris flows</a>. In many respects, the hazards associated with debris flows from burned areas are similar to those from shallow landslides (see Shallow Landslides and Debris Flows section above), although the precipitation thresholds for initiation are often lower.  The USGS has conducted hazard assessments for post-wildfire debris flows for three recent fires in northern and central CA, as well as numerous fires across the Western U.S. including southern California.
</p>
<ul>
  <li><a href="/hazards/postfire_debrisflow/2015/20150731rough/">2015 Rough Fire</a>, Fresno County</li>
  <li><a href="/hazards/postfire_debrisflow/2015/20150909butte/">2015 Butte Fire</a>, Amador and Calaveras Counties</li>
  <li><a href="/hazards/postfire_debrisflow/2015/20150912valley/">2015 Valley Fire</a>, Lake County</li>
</ul>

<h2>Coastal Cliff Erosion</h2>

<figure class="left" style="width:200px">
  <img src="images/cliffs.jpg" alt="three photos of coastal cliffs"/>
  <figcaption>
    Coastal cliffs are subject to wave action as well as precipitation-induced seepage.  These examples from both northern and southern California showcase several different styles of failure. (Photo by Brian Collins, USGS)
  </figcaption>
</figure>

<p>
  Many areas of coastal California are subject to cliff erosion and coastal landslides (see new research on <a href="http://elnino.wr.usgs.gov/">El Ni&ntilde;o coastal hazards</a> in California).  Hazards from these types of landslides can occur both at the bottom of cliffs (from burial) and at the tops of cliffs (from falling over).  During the winter season in California, beaches typically erode thereby allowing waves to reach further inland and to inundate the bottoms of coastal cliffs.  Wave energy is also typically higher during the winter, and particularly during El Ni&ntilde;o events (See <a href="http://www.usgs.gov/newsroom/article.asp?ID=4336&from=rss#.VwwEWRMrJBw">El Ni&ntilde;o and La Ni&ntilde;a Will Exacerbate Coastal Hazards across Entire Pacific</a>), thereby exacerbating the potential for coastal erosion.  <a href="http://landslides.usgs.gov/docs/collins/Collins_sitar_geomorph_2008.pdf">Coastal cliff failures</a> may also occur simply as a result of heightened precipitation as well &ndash; wave action makes cliffs inherently unstable, and rainfall may be the ultimate trigger for failure, even during times with little to no wave action.
</p>
<p>
  During and just after storms, existing coastal landslides may become reactivated and seemingly stable coastal cliffs may erode and fail rapidly.  Background rates of coastal cliff erosion are variable along the California coast (see <a href="http://pubs.usgs.gov/of/2007/1133/">USGS Open File Report 2007-1133</a>) and tied to the rock or soil strength of the cliffs among other factors, but these measurements of historic coastal cliff retreat provide indications of places most susceptible to coastal landslides.
</p>

<h3>Contact Us</h3>
<ul style="list-style-position: inside">
  <li><a href="mailto:bcollins@usgs.gov">Brian Collins</a></li>
  <li><a href="mailto:jstock@usgs.gov">Jonathan Stock</a></li>
</ul>
